[app]
    ServerName = "dm.user.srv"
    Version = "latest"
    Address = ":10086"

[srvcli]
     SrvCli4BaseCli ="dsvo.user.srv.cli"
     SrvCli4RegAddr = "127.0.0.1:2379"
     SrvCli4AuthSrv  ="dsvo.auth.srv"

# 全局日志配置
[logger]
    Path   = "./data/logs"
    Level  = "all"
    Stdout = true

# 数据库连接
[database]
      link  = "mysql:root:root@tcp(127.0.0.1:3306)/userdb"
    debug = true
    # 数据库日志对象配置
    [database.logger]
        Path   = "./data/logs"
        Level  = "all"
        Stdout = true

[redis]
     default  = "127.0.0.1:6379,0"
     cache = "127.0.0.1:6379,1"