// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/user/user.proto

package userSrvPb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SignupReq struct {
	Phone                string   `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Passwd               string   `protobuf:"bytes,2,opt,name=passwd,proto3" json:"passwd,omitempty"`
	RightPasswd          string   `protobuf:"bytes,3,opt,name=right_passwd,json=rightPasswd,proto3" json:"right_passwd,omitempty"`
	Source               string   `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	Ip                   string   `protobuf:"bytes,5,opt,name=ip,proto3" json:"ip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignupReq) Reset()         { *m = SignupReq{} }
func (m *SignupReq) String() string { return proto.CompactTextString(m) }
func (*SignupReq) ProtoMessage()    {}
func (*SignupReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{0}
}

func (m *SignupReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignupReq.Unmarshal(m, b)
}
func (m *SignupReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignupReq.Marshal(b, m, deterministic)
}
func (m *SignupReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignupReq.Merge(m, src)
}
func (m *SignupReq) XXX_Size() int {
	return xxx_messageInfo_SignupReq.Size(m)
}
func (m *SignupReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SignupReq.DiscardUnknown(m)
}

var xxx_messageInfo_SignupReq proto.InternalMessageInfo

func (m *SignupReq) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *SignupReq) GetPasswd() string {
	if m != nil {
		return m.Passwd
	}
	return ""
}

func (m *SignupReq) GetRightPasswd() string {
	if m != nil {
		return m.RightPasswd
	}
	return ""
}

func (m *SignupReq) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *SignupReq) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

type SigninReq struct {
	Phone                string   `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Passwd               string   `protobuf:"bytes,2,opt,name=passwd,proto3" json:"passwd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SigninReq) Reset()         { *m = SigninReq{} }
func (m *SigninReq) String() string { return proto.CompactTextString(m) }
func (*SigninReq) ProtoMessage()    {}
func (*SigninReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{1}
}

func (m *SigninReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SigninReq.Unmarshal(m, b)
}
func (m *SigninReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SigninReq.Marshal(b, m, deterministic)
}
func (m *SigninReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SigninReq.Merge(m, src)
}
func (m *SigninReq) XXX_Size() int {
	return xxx_messageInfo_SigninReq.Size(m)
}
func (m *SigninReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SigninReq.DiscardUnknown(m)
}

var xxx_messageInfo_SigninReq proto.InternalMessageInfo

func (m *SigninReq) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *SigninReq) GetPasswd() string {
	if m != nil {
		return m.Passwd
	}
	return ""
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{2}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type UserSignResp struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserSignResp) Reset()         { *m = UserSignResp{} }
func (m *UserSignResp) String() string { return proto.CompactTextString(m) }
func (*UserSignResp) ProtoMessage()    {}
func (*UserSignResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{3}
}

func (m *UserSignResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserSignResp.Unmarshal(m, b)
}
func (m *UserSignResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserSignResp.Marshal(b, m, deterministic)
}
func (m *UserSignResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserSignResp.Merge(m, src)
}
func (m *UserSignResp) XXX_Size() int {
	return xxx_messageInfo_UserSignResp.Size(m)
}
func (m *UserSignResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UserSignResp.DiscardUnknown(m)
}

var xxx_messageInfo_UserSignResp proto.InternalMessageInfo

func (m *UserSignResp) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func init() {
	proto.RegisterType((*SignupReq)(nil), "dm.user.srv.SignupReq")
	proto.RegisterType((*SigninReq)(nil), "dm.user.srv.SigninReq")
	proto.RegisterType((*Empty)(nil), "dm.user.srv.Empty")
	proto.RegisterType((*UserSignResp)(nil), "dm.user.srv.UserSignResp")
}

func init() {
	proto.RegisterFile("proto/user/user.proto", fileDescriptor_9b283a848145d6b7)
}

var fileDescriptor_9b283a848145d6b7 = []byte{
	// 254 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0x31, 0x4b, 0xc4, 0x40,
	0x10, 0x85, 0x4d, 0x34, 0x91, 0x4c, 0x0e, 0x8b, 0x45, 0x43, 0xb4, 0xd2, 0xc5, 0xc2, 0x2a, 0x82,
	0x56, 0x96, 0x0a, 0xf6, 0x47, 0x0e, 0x1b, 0x1b, 0xf1, 0xee, 0x86, 0xbb, 0x45, 0x6e, 0x77, 0x9c,
	0x4d, 0x22, 0xf6, 0xfe, 0x03, 0xff, 0xb0, 0x64, 0xf6, 0x22, 0x11, 0x44, 0xb0, 0x59, 0x78, 0xef,
	0xcd, 0x7c, 0x3b, 0x3b, 0x0b, 0x47, 0xc4, 0xae, 0x71, 0x97, 0xad, 0x47, 0x96, 0xa3, 0x12, 0xad,
	0xf2, 0xe5, 0xa6, 0x12, 0xe9, 0xb9, 0xd3, 0x1f, 0x11, 0x64, 0x33, 0xb3, 0xb2, 0x2d, 0xd5, 0xf8,
	0xaa, 0x0e, 0x21, 0xa1, 0xb5, 0xb3, 0x58, 0x46, 0xa7, 0xd1, 0x45, 0x56, 0x07, 0xa1, 0x0a, 0x48,
	0xe9, 0xd9, 0xfb, 0xb7, 0x65, 0x19, 0x8b, 0xbd, 0x55, 0xea, 0x0c, 0x26, 0x6c, 0x56, 0xeb, 0xe6,
	0x69, 0x9b, 0xee, 0x4a, 0x9a, 0x8b, 0x37, 0x0d, 0x25, 0x05, 0xa4, 0xde, 0xb5, 0xbc, 0xc0, 0x72,
	0x2f, 0xb4, 0x06, 0xa5, 0x0e, 0x20, 0x36, 0x54, 0x26, 0xe2, 0xc5, 0x86, 0xf4, 0x4d, 0x98, 0xc2,
	0xd8, 0x7f, 0x4f, 0xa1, 0xf7, 0x21, 0xb9, 0xdf, 0x50, 0xf3, 0xae, 0xcf, 0x61, 0xf2, 0xe0, 0x91,
	0x7b, 0x4e, 0x8d, 0x9e, 0x7a, 0x4c, 0xe3, 0x5e, 0xd0, 0x0e, 0x18, 0x11, 0x57, 0x9f, 0x11, 0xe4,
	0x52, 0x86, 0xdc, 0x99, 0x05, 0xaa, 0x5b, 0x80, 0xa1, 0xab, 0x25, 0x55, 0x54, 0xa3, 0xe5, 0x54,
	0xdf, 0x8b, 0x39, 0x39, 0xfe, 0xe1, 0x8f, 0xaf, 0xd1, 0x3b, 0x63, 0x84, 0xb1, 0xbf, 0x20, 0xe4,
	0x55, 0x7f, 0x22, 0xee, 0xf2, 0xc7, 0xac, 0x8f, 0x66, 0xdc, 0x4d, 0xe7, 0xf3, 0x54, 0xfe, 0xe9,
	0xfa, 0x2b, 0x00, 0x00, 0xff, 0xff, 0x4d, 0x91, 0x45, 0x62, 0xc0, 0x01, 0x00, 0x00,
}
