// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/user/user.proto

package userSrvPb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for UserService service

type UserService interface {
	UserSignup(ctx context.Context, in *SignupReq, opts ...client.CallOption) (*UserSignResp, error)
	UserSignin(ctx context.Context, in *SigninReq, opts ...client.CallOption) (*UserSignResp, error)
}

type userService struct {
	c    client.Client
	name string
}

func NewUserService(name string, c client.Client) UserService {
	return &userService{
		c:    c,
		name: name,
	}
}

func (c *userService) UserSignup(ctx context.Context, in *SignupReq, opts ...client.CallOption) (*UserSignResp, error) {
	req := c.c.NewRequest(c.name, "UserService.UserSignup", in)
	out := new(UserSignResp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) UserSignin(ctx context.Context, in *SigninReq, opts ...client.CallOption) (*UserSignResp, error) {
	req := c.c.NewRequest(c.name, "UserService.UserSignin", in)
	out := new(UserSignResp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserService service

type UserServiceHandler interface {
	UserSignup(context.Context, *SignupReq, *UserSignResp) error
	UserSignin(context.Context, *SigninReq, *UserSignResp) error
}

func RegisterUserServiceHandler(s server.Server, hdlr UserServiceHandler, opts ...server.HandlerOption) error {
	type userService interface {
		UserSignup(ctx context.Context, in *SignupReq, out *UserSignResp) error
		UserSignin(ctx context.Context, in *SigninReq, out *UserSignResp) error
	}
	type UserService struct {
		userService
	}
	h := &userServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&UserService{h}, opts...))
}

type userServiceHandler struct {
	UserServiceHandler
}

func (h *userServiceHandler) UserSignup(ctx context.Context, in *SignupReq, out *UserSignResp) error {
	return h.UserServiceHandler.UserSignup(ctx, in, out)
}

func (h *userServiceHandler) UserSignin(ctx context.Context, in *SigninReq, out *UserSignResp) error {
	return h.UserServiceHandler.UserSignin(ctx, in, out)
}
